// Estrutura das 6 seções do playbook
const SECTIONS = [
  {
    id: "produto",
    num: "01",
    title: "Produto & Oferta",
    subtitle: "O que você vende e o valor que entrega",
    icon: "box",
    summary: "Produto, planos, diferenciais e provas de resultado.",
    fields: [
      { id: "nome",         kind: "text",     label: "Nome da empresa",              placeholder: "ex.: Acme Vendas",              col: 6 },
      { id: "nicho",        kind: "text",     label: "Nicho / mercado",              placeholder: "ex.: SaaS jurídico, clínica...", col: 6 },
      { id: "site",         kind: "text",     label: "Site / Instagram",             placeholder: "https:// ou @perfil",           col: 6 },
      { id: "regiao",       kind: "text",     label: "Região de atuação",            placeholder: "ex.: Brasil, LATAM",            col: 6 },
      { id: "vende",        kind: "textarea", label: "O que a empresa vende?",       placeholder: "Produto ou serviço principal — descreva em 2-3 frases", rows: 2 },
      { id: "oferta",       kind: "textarea", label: "Oferta, planos e preços",      placeholder: "Planos disponíveis, o que inclui cada um e faixa de preço / investimento", rows: 3 },
      { id: "transformacao",kind: "textarea", label: "Transformação + diferencial",  placeholder: "Antes vs. depois para o cliente. O que só vocês entregam. Por que escolher vocês?", rows: 3 },
      { id: "promessa",     kind: "text",     label: "Promessa central",             placeholder: "Em 1 frase forte" },
      { id: "resultados",   kind: "textarea", label: "Resultados, cases e ROI",      placeholder: "Ex.: Acme → +312% em pipeline. ROI médio 6x. Depoimentos de clientes...", rows: 4, mono: true },
    ],
  },
  {
    id: "icp",
    num: "02",
    title: "ICP — Cliente Ideal",
    subtitle: "Quem compra, quem fecha, quem dá lucro",
    icon: "target",
    summary: "Perfil exato do cliente que você quer multiplicar.",
    fields: [
      { id: "modelo",       kind: "segmented",label: "Modelo de negócio",            options: ["B2B", "B2C", "B2B2C", "D2C"] },
      { id: "segmento",     kind: "text",     label: "Segmento / setor",             placeholder: "ex.: Indústria moveleira, e-commerce de moda", col: 6 },
      { id: "ticket",       kind: "text",     label: "Ticket médio",                 placeholder: "R$",                                           col: 6 },
      { id: "icp_desc",     kind: "textarea", label: "Quem é o cliente ideal?",      placeholder: "Cargo, contexto, momento da empresa, dores, o que busca — descreva em prosa", rows: 4 },
      { id: "dor_urgencia", kind: "textarea", label: "Dor principal + o que gera urgência", placeholder: "A dor que justifica a compra e os gatilhos que fazem o cliente agir agora", rows: 3 },
      { id: "qualifica",    kind: "textarea", label: "Qualifica vs. Desqualifica",   placeholder: "O que indica um lead bom (critérios de qualificação) e o que elimina (red flags)", rows: 3 },
    ],
  },
  {
    id: "vendas",
    num: "03",
    title: "Script de Vendas",
    subtitle: "Tom, processo e objeções",
    icon: "flow",
    summary: "Como abordar, qualificar, fechar e tratar objeções.",
    fields: [
      { id: "canais",       kind: "chips",    label: "De onde vêm os leads?",        placeholder: "Adicionar canal + Enter", suggestions: ["Inbound", "Outbound", "Indicação", "Tráfego pago", "Eventos", "Parcerias", "LinkedIn", "WhatsApp"] },
      { id: "processo",     kind: "textarea", label: "Processo de venda",            placeholder: "Do primeiro contato ao fechamento — etapas, como funciona cada uma, tempo médio", rows: 3 },
      { id: "objecoes",     kind: "chips",    label: "Objeções mais comuns",         placeholder: "Adicionar + Enter", suggestions: ["Preço alto", "Sem orçamento", "Vou pensar", "Já uso outro", "Não é prioridade", "Falar com sócio", "Não tenho tempo"] },
      { id: "formal",       kind: "scale",    label: "Formalidade",                  left: "Informal", right: "Formal" },
      { id: "energia",      kind: "scale",    label: "Energia",                      left: "Premium / calma", right: "Agressiva / direta" },
      { id: "estilo",       kind: "scale",    label: "Estilo",                       left: "Direto", right: "Consultivo" },
      { id: "palavras_sim", kind: "chips",    label: "Palavras que vocês usam",      placeholder: "Adicionar + Enter" },
      { id: "palavras_nao", kind: "chips",    label: "Palavras proibidas",           placeholder: "Adicionar + Enter" },
      { id: "exemplo",      kind: "textarea", label: "Exemplo de mensagem ideal",    placeholder: "Cole um trecho real que represente o tom — WhatsApp, e-mail, roteiro de call...", rows: 3, mono: true },
    ],
  },
  {
    id: "time",
    num: "04",
    title: "Time Comercial",
    subtitle: "Quem vende, metas e rituais",
    icon: "chart",
    summary: "Estrutura do time, KPIs, SLAs e rotina operacional.",
    fields: [
      { id: "equipe",       kind: "textarea", label: "Equipe comercial",             placeholder: "Cargos, quantidade e responsabilidades. Ex.: 2 SDRs, 3 Closers, 1 CS", rows: 3 },
      { id: "conversao",    kind: "text",     label: "Conversão lead → cliente",     placeholder: "ex.: 12%",  col: 4 },
      { id: "vol_leads",    kind: "text",     label: "Leads por mês",                placeholder: "ex.: 320",  col: 4 },
      { id: "tempo_fech",   kind: "text",     label: "Tempo médio de fechamento",    placeholder: "ex.: 18d",  col: 4 },
      { id: "meta",         kind: "textarea", label: "Meta dos próximos 90 dias",    placeholder: "Receita, novos clientes, taxa de conversão, canais...", rows: 2 },
      { id: "sla_rituais",  kind: "textarea", label: "SLAs e rituais do time",       placeholder: "Tempo de resposta, daily de vendas, reunião de pipeline, review mensal...", rows: 2 },
    ],
  },
  {
    id: "cultura",
    num: "05",
    title: "Manual de Cultura",
    subtitle: "Identidade, valores e jeito de ser",
    icon: "spark",
    summary: "O que guia o time além das métricas.",
    fields: [
      { id: "percepcao",    kind: "chips",    label: "Como deseja ser percebida?",   placeholder: "Adicionar atributo + Enter", suggestions: ["Premium", "Consultiva", "Técnica", "Próxima", "Inovadora", "Confiável", "Ágil", "Humana", "Especialista"] },
      { id: "proposito",    kind: "textarea", label: "Propósito e missão comercial", placeholder: "Por que a empresa existe além de lucrar. O que o time de vendas existe para fazer no mundo.", rows: 3 },
      { id: "valores",      kind: "chips",    label: "Valores da empresa",           placeholder: "Adicionar valor + Enter", suggestions: ["Resultado", "Transparência", "Excelência", "Inovação", "Cliente no centro", "Integridade", "Velocidade"] },
      { id: "conduta",      kind: "textarea", label: "O que fazemos e o que NUNCA fazemos", placeholder: "Comportamentos esperados do time e linhas vermelhas inegociáveis", rows: 3 },
    ],
  },
  {
    id: "operacao",
    num: "06",
    title: "Mapa de Operação",
    subtitle: "Ferramentas, processos e visual do playbook",
    icon: "gear",
    summary: "Stack, funil, gargalos e identidade visual.",
    fields: [
      { id: "crm",          kind: "text",     label: "CRM utilizado",                placeholder: "ex.: HubSpot, Pipedrive, RD Station", col: 6 },
      { id: "ferramentas",  kind: "chips",    label: "Ferramentas do time",          placeholder: "Adicionar + Enter", suggestions: ["WhatsApp Business", "Notion", "Slack", "Loom", "Apollo", "Calendly", "Make", "Zapier", "Google Meet"] },
      { id: "funis",        kind: "textarea", label: "Funil de vendas (resumo)",     placeholder: "Etapas do funil e critério de avanço em cada uma (resumo rápido)", rows: 2 },
      { id: "fluxo_mapa",   kind: "flowbuilder", label: "Fluxograma do Processo Comercial" },
      { id: "onboarding",   kind: "textarea", label: "Onboarding do cliente",        placeholder: "Como entregam o que venderam — primeiros passos após o fechamento", rows: 2 },
      { id: "gargalos",     kind: "textarea", label: "Gargalos atuais",              placeholder: "Onde a operação trava hoje", rows: 2 },
      { id: "visual_preset",kind: "visualpreset", label: "Visual do playbook" },
      { id: "cor_primaria", kind: "text",     label: "Cor primária",                 placeholder: "#3b82f6 ou 'azul royal'",  col: 4 },
      { id: "cor_secundaria",kind:"text",     label: "Cor secundária",               placeholder: "#6366f1 ou 'índigo'",      col: 4 },
      { id: "cor_fundo",    kind: "text",     label: "Cor de fundo",                 placeholder: "#0f172a ou 'branco'",      col: 4 },
      { id: "fonte",        kind: "segmented",label: "Tipografia",                   options: ["Inter", "Poppins", "Montserrat", "Sora"] },
      { id: "mood",         kind: "chips",    label: "Mood visual",                  placeholder: "Adicionar + Enter", suggestions: ["Minimalista", "Sofisticado", "Tecnológico", "Humanizado", "Premium", "Arrojado", "Clean", "Corporativo"] },
      { id: "logo_desc",    kind: "textarea", label: "Logo e identidade visual",     placeholder: "Cores da marca, fontes usadas, slogan, como é o logo", rows: 2 },
      { id: "uploads",      kind: "upload",   label: "Materiais de apoio",           accept: "PDFs, DOCX, imagens, planilhas, apresentações — qualquer material relevante para a IA." },
      { id: "obs_material", kind: "textarea", label: "Observações sobre os materiais", placeholder: "Contexto sobre os arquivos: prioridades, o que a IA deve focar ou ignorar", rows: 2 },
    ],
  },
];

window.SECTIONS = SECTIONS;

/* Presets de identidade visual */
window.VISUAL_PRESETS = {
  "Dark Premium": {
    cor_primaria: "#3b82f6",
    cor_secundaria: "#6366f1",
    cor_acento: "#8b5cf6",
    cor_fundo: "#0f172a",
    fonte: "Inter",
    mood: ["Dark", "Premium", "Tecnológico", "Minimalista"],
    estilo_desc: "Visual escuro e sofisticado. Fundo profundo azul-marinho com acentos em azul elétrico e roxo. Tipografia forte Inter. Estilo SaaS premium — Linear, Stripe, Vercel.",
  },
  "Light Clean": {
    cor_primaria: "#1e293b",
    cor_secundaria: "#3b82f6",
    cor_acento: "#10b981",
    cor_fundo: "#f8fafc",
    fonte: "Inter",
    mood: ["Clean", "Profissional", "Claro", "Moderno"],
    estilo_desc: "Visual claro e limpo. Fundo branco com elementos em azul-escuro e verde-esmeralda. Leve, profissional e de fácil leitura.",
  },
  "Corporativo": {
    cor_primaria: "#1a1a2e",
    cor_secundaria: "#c9a84c",
    cor_acento: "#e8d5b7",
    cor_fundo: "#ffffff",
    fonte: "Montserrat",
    mood: ["Corporativo", "Sofisticado", "Sério", "Elegante"],
    estilo_desc: "Visual corporativo premium. Fundo branco com azul-marinho profundo e dourado como acento. Elegância e autoridade. Referência: consultoria e finanças.",
  },
  "Minimalista": {
    cor_primaria: "#111827",
    cor_secundaria: "#374151",
    cor_acento: "#f59e0b",
    cor_fundo: "#fafafa",
    fonte: "Sora",
    mood: ["Minimalista", "Clean", "Leve", "Editorial"],
    estilo_desc: "Visual extremamente limpo. Fundo quase-branco com texto escuro e toque âmbar como destaque. Espaçamento generoso. Estilo editorial.",
  },
};
