/* ─────────────────────────────────────────────────────────────────────────
 * VX · TEMPLATES
 * Templates pré-preenchidos por nicho para servir como base do playbook.
 * ───────────────────────────────────────────────────────────────────────── */

window.VX_TEMPLATES = [
  /* ──────────────────────────────────────────────────────
   * 01. CONSULTORIA COMERCIAL B2B
   * ────────────────────────────────────────────────────── */
  {
    id: "consultoria-b2b",
    name: "Consultoria Comercial B2B",
    description: "Treinamento de equipes, reestruturação de funil e aceleração de receita para empresas B2B.",
    tags: ["B2B", "Consultoria", "Vendas", "Treinamento"],
    color: "#ff5b15",
    icon: "chart",
    data: {
      empresa: {
        nome: "Sua Consultoria",
        site: "https://suaconsultoria.com.br",
        instagram: "@suaconsultoria",
        nicho: "Consultoria comercial B2B",
        tempo: "4 anos",
        regiao: "Brasil",
        funcionarios: "8",
        estrutura: "2 consultores sênior, 1 gestor de projetos, 1 analista de dados, suporte administrativo",
        vende: "Reestruturação de operações comerciais: diagnóstico do funil, treinamento de equipes de vendas, implementação de CRM, criação de playbooks e acompanhamento de resultados por 90 dias.",
        transformacao: "Empresas que faturavam de forma inconsistente e dependiam do dono para vender passam a ter operação previsível, com time comercial autônomo e funil estruturado.",
        diferencial: "Não vendemos treinamento genérico — entregamos um playbook 100% customizado com a linguagem, os processos e os clientes do próprio negócio. Acompanhamos a execução, não só a teoria.",
        promessa: "Sua operação comercial previsível e escalável em 90 dias.",
        percepcao: ["Consultiva", "Premium", "Técnica", "Confiável"],
      },
      icp: {
        segmento: "Empresas de serviços e tecnologia",
        setor: "B2B — ticket médio acima de R$ 3.000",
        modelo: "B2B",
        icp_desc: "Empresário ou diretor comercial de empresa com 5 a 50 funcionários, faturamento entre R$ 500k e R$ 5M/ano, que já tem produto validado mas opera de forma reativa — sem CRM, sem script, sem funil estruturado. Sente que depende demais de si mesmo para vender.",
        ticket: "R$ 12.000 a R$ 35.000",
        fat_ideal: "R$ 1M a R$ 10M/ano",
        estrutura_min: "1+ vendedor ou sócio que vende",
        dor_principal: "A operação comercial depende do dono. Sem ele prospectando ou fechando, as vendas param. O time não sabe o que dizer, não faz follow-up e perde leads por falta de processo.",
        perde_vendas: "Cliente pede proposta e some. Follow-up não acontece. Time não sabe contornar objeções. Preço vira o único argumento.",
        urgencia: "Mês ruim de vendas, sócio pressionando por resultado, concorrente crescendo, ou meta do próximo trimestre impossível sem mudança de estrutura.",
      },
      oferta: {
        oferta: "Programa de Reestruturação Comercial — diagnóstico + playbook + treinamento + 90 dias de acompanhamento semanal.",
        produtos: ["Diagnóstico Comercial", "Playbook de Vendas Customizado", "Treinamento de Equipe", "Implementação de CRM"],
        servicos: ["Mentoria Semanal", "Auditoria de Funil", "Scripts Personalizados", "Dashboard de Performance"],
        planos: "Start (R$ 12k): Diagnóstico + Playbook + 1 treinamento\nGrow (R$ 22k): Tudo do Start + CRM + 90 dias de acompanhamento\nScale (R$ 35k): Tudo do Grow + implantação completa + gestor dedicado por 90 dias",
        precos: "Entrada: 30% na assinatura, saldo em até 2x. Parcelamento em cartão em até 6x. Sem desconto por pagamento à vista acima de 5%.",
        beneficios: ["Playbook 100% customizado", "Scripts prontos para uso", "CRM configurado", "Dashboard de KPIs", "Acompanhamento semanal", "Suporte via WhatsApp"],
        resultados: "Aumento médio de 35% na taxa de conversão nos primeiros 90 dias. Time vendendo sem depender do dono. Funil previsível com SLAs definidos.",
        melhora: "O dono para de ser o único vendedor. O time ganha autonomia. A empresa passa a ter previsibilidade de receita.",
        economia: "Redução de 40% no custo de aquisição por cliente ao sistematizar prospecção e qualificação.",
        diferenciais: "1. Acompanhamento real de execução — não é só material entregue\n2. Playbook com a linguagem e os clientes da própria empresa\n3. Resultado mensurável com KPIs acompanhados semanalmente",
        porque: "Porque não vendemos metodologia genérica. Mergulhamos na sua operação, criamos o playbook da sua empresa e ficamos do seu lado até o resultado aparecer.",
      },
      processo: {
        canais: ["Indicação", "LinkedIn", "Eventos", "Parcerias"],
        canal_top: "Indicação — converte 40% dos contatos em clientes",
        qualifica: "BANT adaptado: Budget (tem orçamento ou busca ROI claro?), Authority (é o decisor?), Need (operação comercial trávada?), Timeline (urgência real nos próximos 60 dias?). Mínimo: empresa com faturamento acima de R$ 500k e ao menos 1 pessoa dedicada a vendas.",
        desqualifica: "Empresa sem time comercial definido e sem intenção de contratar. Faturamento abaixo de R$ 300k. Empresário que quer resultado sem participar do processo.",
        reuniao: "Sim",
        script: "Sim",
        apresentacao: "Sim",
        fechamento: "Reunião de diagnóstico (60 min) → proposta personalizada em 48h → reunião de apresentação → contrato → kickoff em até 7 dias.",
        proposta: "PDF com diagnóstico inicial, proposta de solução personalizada, cronograma, investimento e casos similares. Enviada em 48h após a reunião.",
        negociacao: "Desconto máximo de 5% em pagamento à vista. Parcelamento flexível. Não negociamos escopo — se o cliente precisa de menos, oferecemos o plano Start.",
        entregam: "Kickoff com todos os envolvidos, alinhamento de expectativas, cronograma detalhado das semanas. Entrega semanal com reunião de acompanhamento.",
        onboarding: "Sim",
      },
      objecoes: {
        obj_comum: "\"É muito caro para o momento da empresa.\"",
        obj_lista: ["Preço alto", "Vou pensar", "Falar com sócio", "Já tentei consultoria antes", "Não é prioridade agora"],
        impede: "Medo de investir e não ver resultado. Experiências ruins com consultorias anteriores que entregaram material e sumiram. Indefinição de quem decide na empresa.",
        inseguranca: "\"E se o meu time não adotar?\", \"E se eu não tiver tempo?\", \"Como sei que vai funcionar para o meu nicho?\"",
      },
      metricas: {
        conversao: "22% (reunião → cliente)",
        ticket_med: "R$ 22.000",
        cac: "R$ 2.800",
        tempo_fech: "14 dias",
        vol_leads: "35/mês",
        meta: "Meta Q3: R$ 180k em novos contratos. KPIs: 8 reuniões/semana, 3 propostas enviadas, 1,8 fechamentos. Foco em escalar canal de parcerias para 25% do volume.",
        sla: "Resposta a leads em até 2h. Proposta enviada em 48h. Reunião de follow-up em até 5 dias da proposta.",
      },
      operacao: {
        crm: "HubSpot (CRM gratuito com pipeline personalizado)",
        whats: "WhatsApp Business com catálogo e respostas rápidas configuradas",
        ferramentas: ["Notion", "HubSpot", "Calendly", "Loom", "Google Meet", "Canva"],
        equipe: "2 consultores sênior (fechamento e entrega), 1 SDR (prospecção e qualificação), 1 analista (dados e dashboard), 1 assistente (administrativo e CS)",
        funis: "Funil 1 — Aquisição: Lead > Contato > Qualificado > Reunião > Proposta > Fechado\nFunil 2 — Entrega: Kickoff > Diagnóstico > Playbook > Treinamento > Acompanhamento > Renovação",
        processos: "Cadência de prospecção: 3 contatos em 7 dias. Follow-up de proposta: dia 2, dia 5, dia 10. Reunião semanal de pipeline às segundas. Dashboard atualizado sexta.",
        gargalos: "Volume de leads ainda baixo para a capacidade de entrega. Follow-up pós-proposta inconsistente. Onboarding de novos clientes demora mais do que deveria.",
      },
      tom: {
        formal: 55,
        agressiva: 40,
        consultiva: 75,
        tecnica: 60,
        palavras_sim: ["operação", "resultado", "previsibilidade", "estrutura", "escalar", "processo", "diagnóstico"],
        palavras_nao: ["barato", "simples", "rápido", "fácil", "garantido", "perfeito"],
        exemplo: "Vitor, identificamos 3 pontos críticos na sua operação que estão limitando o crescimento: ausência de script estruturado, follow-up manual e sem CRM. Nosso programa resolve isso em 90 dias com acompanhamento semanal. Posso te mostrar como funcionou para a Empresa X no mesmo setor?",
      },
      cases: {
        cases: "Distribuidora Alfa — +68% em conversão em 60 dias após implementação do playbook\nAgência Beta — time de 5 vendedores autônomo em 45 dias, dono saiu das vendas\nTech Gama — pipeline previsível: de R$ 80k/mês para R$ 210k/mês em 3 meses",
        resultados: "Média de +38% em conversão. 100% dos clientes com CRM ativo após 30 dias. NPS médio de 87.",
        roi: "4x a 8x no primeiro ciclo de 90 dias",
        depoimentos: "\"Em 6 semanas meu time vendeu mais do que no trimestre inteiro. O playbook foi divisor de águas.\" — João, CEO Distribuidora Alfa\n\"Finalmente parei de ser o único vendedor da empresa.\" — Marina, fundadora Agência Beta",
      },
      material: {
        obs_material: "Temos cases documentados em PDF. Proposta comercial padrão disponível. Apresentação institucional atualizada.",
      },
    },
  },

  /* ──────────────────────────────────────────────────────
   * 02. AGÊNCIA DE MARKETING DIGITAL
   * ────────────────────────────────────────────────────── */
  {
    id: "agencia-marketing",
    name: "Agência de Marketing Digital",
    description: "Tráfego pago, gestão de redes sociais, conteúdo e performance para empresas locais e e-commerces.",
    tags: ["Marketing", "Tráfego Pago", "Social Media", "B2B", "B2C"],
    color: "#6366f1",
    icon: "spark",
    data: {
      empresa: {
        nome: "Sua Agência",
        site: "https://suaagencia.com.br",
        instagram: "@suaagencia",
        nicho: "Marketing digital — tráfego pago e gestão de redes",
        tempo: "3 anos",
        regiao: "Brasil",
        funcionarios: "12",
        estrutura: "1 head de tráfego, 2 gestores de mídia, 2 criadores de conteúdo, 1 designer, 1 copywriter, 1 analista de dados, CS, comercial",
        vende: "Gestão de tráfego pago (Meta Ads, Google Ads), gestão de redes sociais, produção de conteúdo, criação de landing pages e estratégia de performance.",
        transformacao: "Empresas que gastavam verba em anúncios sem retorno passam a ter campanhas lucrativas, previsíveis e escaláveis com ROI mensurável.",
        diferencial: "Não gerenciamos anúncio — gerenciamos resultado. Cada cliente tem um gestor dedicado, dashboard em tempo real e reunião quinzenal de performance.",
        promessa: "Mais leads qualificados, menos desperdício de verba.",
        percepcao: ["Técnica", "Confiável", "Inovadora", "Próxima"],
      },
      icp: {
        segmento: "Pequenas e médias empresas locais e e-commerces",
        setor: "Varejo, saúde, educação, serviços — B2C e B2B",
        modelo: "B2B",
        icp_desc: "Dono de negócio ou diretor de marketing com verba mensal de R$ 3k a R$ 50k em anúncios, que já tentou gerenciar sozinho ou teve experiência ruim com agência anterior. Quer resultado mensurável, não só relatório bonito.",
        ticket: "R$ 2.500 a R$ 8.000/mês",
        fat_ideal: "R$ 500k a R$ 10M/ano",
        estrutura_min: "Produto ou serviço validado, verba mínima de R$ 2.000/mês para anúncios",
        dor_principal: "Gastar com anúncios sem saber o que está funcionando. Relatórios confusos. Agência que some e não responde. Leads que chegam mas não convertem.",
        perde_vendas: "Cliente compara somente por preço. Não confia que a agência vai entregar resultado diferente das anteriores. Quer resultado rápido mas tem produto/oferta fraca.",
        urgencia: "Produto novo para lançar, concorrente crescendo no digital, ou verba desperdiçada por meses sem resultado.",
      },
      oferta: {
        oferta: "Gestão de tráfego pago com estratégia, criação, otimização diária e relatório de performance semanal.",
        produtos: ["Gestão de Meta Ads", "Gestão de Google Ads", "Gestão de TikTok Ads", "Landing Pages de Alta Conversão"],
        servicos: ["Gestão de Redes Sociais", "Produção de Conteúdo", "Copywriting", "Email Marketing", "SEO"],
        planos: "Launch (R$ 2.500/mês): 1 canal de tráfego, gestão básica\nGrow (R$ 4.500/mês): 2 canais, criação de conteúdo inclusa, relatório semanal\nScale (R$ 8.000/mês): todos os canais, produção full, CS dedicado, reunião quinzenal",
        precos: "Contrato mínimo de 3 meses. Verba de anúncios separada (cliente paga direto às plataformas). Sem taxa de setup.",
        beneficios: ["Gestor dedicado", "Dashboard em tempo real", "Criativo testado", "Reunião quinzenal", "WhatsApp direto com gestor", "Sem taxa de cancelamento após 3 meses"],
        resultados: "Redução média de 30% no CPL. Aumento de 2x a 5x no ROAS em 60 dias de otimização.",
        melhora: "Dono para de se preocupar com anúncios e foca no produto. Leads chegando com previsibilidade.",
        economia: "Eliminação de verba desperdiçada — média de 25% da verba era gasta em públicos sem conversão.",
        diferenciais: "1. Dashboard em tempo real — cliente vê tudo acontecer\n2. Reunião quinzenal de estratégia — não só relatório\n3. Criativo e copy inclusos nos planos — não precisa contratar fora",
        porque: "Porque cada R$ de verba precisa trabalhar. Não entregamos impressões, entregamos leads qualificados e ROAS positivo.",
      },
      processo: {
        canais: ["Indicação", "Instagram", "LinkedIn", "Parcerias", "Tráfego pago próprio"],
        canal_top: "Indicação — 50% dos clientes novos vêm de indicação de clientes ativos",
        qualifica: "Verba disponível acima de R$ 1.500/mês para anúncios. Produto ou serviço com demanda comprovada. Decisor disponível para reunião. Expectativa alinhada com realidade (não espera milagre em 7 dias).",
        desqualifica: "Verba abaixo de R$ 1.000/mês. Produto sem validação. Empresário que vai \"supervisionar\" tudo e bloquear criativos.",
        reuniao: "Sim",
        script: "Sim",
        apresentacao: "Sim",
        fechamento: "Reunião de diagnóstico (45 min) → análise gratuita da conta de anúncios em 24h → proposta personalizada → contrato → onboarding em 5 dias.",
        proposta: "PDF com análise da conta atual (se houver), oportunidades identificadas, plano de ação, planos e investimento.",
        negociacao: "Contrato semestral tem 10% de desconto. Plano anual tem 15%. Sem desconto em contratos mensais.",
        entregam: "Onboarding: acesso às contas, briefing de marca, criação das primeiras campanhas em 5 dias úteis.",
        onboarding: "Sim",
      },
      objecoes: {
        obj_comum: "\"Já tive agência e não funcionou.\"",
        obj_lista: ["Preço alto", "Já uso outro", "Vou pensar", "Não é o momento", "Quero resultado rápido"],
        impede: "Desconfiança por experiências ruins anteriores. Dificuldade de enxergar o valor além do preço.",
        inseguranca: "\"Como sei que dessa vez vai ser diferente?\" — trabalhamos com contrato de 3 meses e dashboard transparente.",
      },
      metricas: {
        conversao: "28% (reunião → cliente)",
        ticket_med: "R$ 4.200/mês",
        cac: "R$ 1.200",
        tempo_fech: "10 dias",
        vol_leads: "80/mês",
        meta: "Meta: 25 clientes ativos até dezembro. Churn máximo de 8%/mês. LTV alvo: R$ 25.000.",
        sla: "Resposta em até 4h no horário comercial. Primeira campanha no ar em 5 dias úteis. Relatório semanal toda sexta.",
      },
      operacao: {
        crm: "RD Station CRM",
        whats: "WhatsApp Business + Evolution API para automações",
        ferramentas: ["Meta Business Suite", "Google Ads", "Google Analytics", "Data Studio", "Notion", "Slack", "Canva", "CapCut"],
        equipe: "1 head de tráfego, 2 gestores de mídia (4 clientes cada), 2 criadores de conteúdo, 1 designer, 1 CS, 1 comercial",
        funis: "Funil Comercial: Lead > Qualificação > Reunião > Proposta > Fechamento\nFunil de Entrega: Onboarding > Campanha Live > Otimização > Relatório > Renovação",
        processos: "Daily de 15 min com gestores toda manhã. Reunião de performance com clientes quinzenal. Relatório enviado automaticamente toda sexta.",
        gargalos: "Onboarding de novos clientes consome muito tempo do gestor. Churn nos primeiros 3 meses ainda alto. Produção de criativo é gargalo quando há muitos clientes simultâneos.",
      },
      tom: {
        formal: 40,
        agressiva: 55,
        consultiva: 60,
        tecnica: 65,
        palavras_sim: ["resultado", "performance", "ROI", "conversão", "escalável", "dados", "estratégia"],
        palavras_nao: ["viral", "orgânico milagre", "garantimos X leads", "simples assim"],
        exemplo: "Ana, analisamos sua conta de anúncios e identificamos R$ 1.800/mês sendo desperdiçados em públicos frios. Com a reestruturação das campanhas, clientes similares reduziram CPL em 35% no primeiro mês. Quer ver o diagnóstico completo?",
      },
      cases: {
        cases: "Clínica Estética SP — CPL de R$ 48 para R$ 18 em 45 dias\nE-commerce Moda — ROAS de 1.8x para 4.2x em 60 dias\nEscola de Idiomas — 3x mais matrículas no mesmo investimento",
        resultados: "Média de redução de 35% no CPL. ROAS médio de 3.8x nos clientes ativos há mais de 6 meses.",
        roi: "3x a 6x no ROAS após otimização",
        depoimentos: "\"Antes gastava R$ 5k/mês e não sabia se funcionava. Agora vejo cada lead chegando em tempo real.\" — Pedro, dono de clínica",
      },
      material: { obs_material: "" },
    },
  },

  /* ──────────────────────────────────────────────────────
   * 03. SAAS / SOFTWARE B2B
   * ────────────────────────────────────────────────────── */
  {
    id: "saas-b2b",
    name: "SaaS / Software B2B",
    description: "Software de gestão, automação ou inteligência para empresas. Modelo de assinatura recorrente.",
    tags: ["SaaS", "B2B", "Recorrente", "Tech", "Software"],
    color: "#3b82f6",
    icon: "gear",
    data: {
      empresa: {
        nome: "Seu Software",
        site: "https://seusoftware.com.br",
        instagram: "@seusoftware",
        nicho: "SaaS B2B — gestão e automação",
        tempo: "2 anos",
        regiao: "Brasil",
        funcionarios: "18",
        estrutura: "CTO + dev team (6), comercial (3 AEs + 2 SDRs), CS (2), marketing (2), operações (2)",
        vende: "Plataforma SaaS de gestão e automação que centraliza processos, elimina trabalho manual e entrega dados em tempo real para tomada de decisão.",
        transformacao: "Empresas que operam com planilhas, WhatsApp e processos manuais passam a ter operação centralizada, automatizada e orientada por dados.",
        diferencial: "Implementação em menos de 7 dias. Sem precisar de TI interno. Suporte em português com SLA de 2h. Integração nativa com as principais ferramentas do mercado.",
        promessa: "Sua operação rodando em um único sistema em 7 dias.",
        percepcao: ["Técnica", "Inovadora", "Confiável", "Premium"],
      },
      icp: {
        segmento: "Empresas de médio porte com processos manuais",
        setor: "Serviços, Indústria, Educação, Saúde — B2B",
        modelo: "B2B",
        icp_desc: "Gestor de operações, CEO ou diretor de TI de empresa com 20 a 200 funcionários. Opera com múltiplas ferramentas desconectadas (planilha, e-mail, WhatsApp). Perde tempo com retrabalho e não tem visibilidade dos dados em tempo real.",
        ticket: "R$ 1.200 a R$ 4.500/mês",
        fat_ideal: "R$ 2M a R$ 50M/ano",
        estrutura_min: "20+ funcionários, processos com pelo menos 3 etapas manuais",
        dor_principal: "Informação espalhada em planilhas, WhatsApp e sistemas que não conversam. Gestores tomam decisão sem dados. Retrabalho consome 30% do tempo da equipe.",
        perde_vendas: "Ciclo de vendas longo (múltiplos decisores). Medo de mudança de sistema. Comparação com concorrentes mais baratos sem entender o valor.",
        urgencia: "Auditoria próxima, crescimento rápido tornando o caos insustentável, ou erro operacional que gerou prejuízo.",
      },
      oferta: {
        oferta: "Plataforma SaaS com onboarding guiado, implementação em 7 dias e suporte dedicado nos primeiros 30 dias.",
        produtos: ["Módulo de Gestão de Processos", "Módulo de CRM Integrado", "Módulo de Relatórios e BI", "Módulo de Automação"],
        servicos: ["Implementação Guiada", "Treinamento da Equipe", "Integração com Sistemas Legados", "Consultoria de Processos"],
        planos: "Starter (R$ 1.200/mês): até 15 usuários, módulos básicos\nProfessional (R$ 2.500/mês): até 50 usuários, todos os módulos, API\nEnterprise (R$ 4.500/mês): usuários ilimitados, SLA prioritário, success manager dedicado",
        precos: "Anual com 20% de desconto. Semestral com 10%. Mensal sem desconto. Trial gratuito de 14 dias sem cartão.",
        beneficios: ["Trial 14 dias grátis", "Implementação em 7 dias", "Suporte em PT-BR 2h SLA", "Integrações nativas", "Treinamento incluído", "Dados exportáveis a qualquer momento"],
        resultados: "Redução média de 65% no tempo gasto em retrabalho. Visibilidade total dos processos em tempo real. Decisões baseadas em dados.",
        melhora: "Gestores focam em estratégia em vez de apagar incêndios. Equipe para de fazer o mesmo trabalho duas vezes.",
        economia: "Média de R$ 8.000/mês economizados em horas de retrabalho para empresas de 30 funcionários.",
        diferenciais: "1. Implementação em 7 dias (concorrentes levam 60+)\n2. Suporte em PT-BR com SLA de 2h\n3. Interface que qualquer funcionário aprende em 1 hora",
        porque: "Porque não somos apenas software — somos a operação funcionando. Ficamos do seu lado até o sistema estar rodando e o time adotado.",
      },
      processo: {
        canais: ["Inbound", "Outbound", "Indicação", "Tráfego pago", "Parcerias"],
        canal_top: "Inbound (SEO + conteúdo) — 60% dos trials",
        qualifica: "GPCT: Goal (qual processo quer resolver?), Plan (tem orçamento e timeline?), Challenge (qual a dor principal?), Timeline (urgência para implementar?). Mínimo: 20 funcionários, decisor presente, orçamento confirmado.",
        desqualifica: "Menos de 10 funcionários. Quer apenas planilha melhorada. Sem decisor no processo.",
        reuniao: "Sim",
        script: "Sim",
        apresentacao: "Sim",
        fechamento: "Trial de 14 dias → call de discovery (30 min) → demo personalizada → proposta → fechamento → onboarding.",
        proposta: "Proposta enviada em 24h após demo, com ROI calculado baseado nos dados do cliente (horas, equipe, processos mapeados).",
        negociacao: "Desconto máximo: 15% em contrato anual. Nunca desconto em mensal — oferecemos trial estendido.",
        entregam: "Kickoff com CS dedicado. Configuração do ambiente em D+1. Treinamento básico em D+3. Dados migrados em D+5. Go-live em D+7.",
        onboarding: "Sim",
      },
      objecoes: {
        obj_comum: "\"Vou pensar e volto em contato.\"",
        obj_lista: ["Preço alto", "Sem orçamento agora", "Já uso outro sistema", "Minha equipe não vai adotar", "Não é prioridade"],
        impede: "Medo de migração de dados. Resistência do time à mudança. Ciclo de aprovação interno longo.",
        inseguranca: "\"E os meus dados atuais?\" — migramos tudo. \"E se o time não usar?\" — treinamento incluído e adoção monitorada pelo CS.",
      },
      metricas: {
        conversao: "18% (trial → cliente pago)",
        ticket_med: "R$ 2.100/mês",
        cac: "R$ 4.200",
        tempo_fech: "28 dias",
        vol_leads: "150 trials/mês",
        meta: "MRR alvo: R$ 180k até dezembro. Churn mensal máximo: 3%. NPS alvo: 65+.",
        sla: "Suporte: resposta em 2h. Bug crítico: resolução em 4h. Onboarding: go-live em 7 dias. Trial: primeiro contato em até 1h após cadastro.",
      },
      operacao: {
        crm: "HubSpot CRM (pipeline de trials e fechamentos)",
        whats: "Intercom para suporte in-app + WhatsApp para CS",
        ferramentas: ["HubSpot", "Intercom", "Mixpanel", "Stripe", "Notion", "Slack", "Loom", "Calendly"],
        equipe: "2 SDRs (prospecção outbound), 3 AEs (fechamento), 2 CSMs (sucesso do cliente), 6 devs, 2 marketing, CTO, CEO",
        funis: "Funil Comercial: MQL > SQL > Trial > Demo > Proposta > Fechado\nFunil CS: Onboarding > Adoção > Expansão > Renovação",
        processos: "Trial: contato em 1h, check-in D+3, D+7, D+14. CS: reunião mensal com clientes acima de R$ 2k MRR. Expansão: oferta de upgrade a cada 6 meses.",
        gargalos: "Taxa de conversão trial→pago abaixo da meta. Onboarding ainda muito dependente do CS. Churn nos primeiros 90 dias ainda alto.",
      },
      tom: {
        formal: 50,
        agressiva: 35,
        consultiva: 70,
        tecnica: 75,
        palavras_sim: ["operação", "dados", "automação", "visibilidade", "integração", "eficiência", "escalável"],
        palavras_nao: ["fácil", "rápido", "mágico", "perfeito", "revolucionário"],
        exemplo: "Carlos, vi que sua equipe ainda usa 4 planilhas diferentes para controlar o mesmo processo. Clientes com estrutura similar reduziram o retrabalho em 60% no primeiro mês. Posso te mostrar em 20 minutos como ficaria a operação de vocês no sistema?",
      },
      cases: {
        cases: "Distribuidora Delta — 65% menos retrabalho, zero erros de pedido\nEscola Sigma — gestão de 800 alunos centralizada, 3 funcionários a menos no administrativo\nClínica Omega — laudos e prontuários integrados, 40% mais consultas/dia",
        resultados: "NPS médio de 72. Churn médio de 2,8%/mês. 94% dos clientes renovam no 1º ano.",
        roi: "ROI médio de 5x no primeiro ano considerando horas economizadas",
        depoimentos: "\"Em 2 semanas minha equipe parou de usar planilha. Parece mentira.\" — Fernanda, diretora de operações",
      },
      material: { obs_material: "" },
    },
  },

  /* ──────────────────────────────────────────────────────
   * 04. CLÍNICA / SAÚDE
   * ────────────────────────────────────────────────────── */
  {
    id: "clinica-saude",
    name: "Clínica / Saúde",
    description: "Clínicas médicas, odontológicas, estéticas ou profissionais de saúde que querem crescer com previsibilidade.",
    tags: ["Saúde", "Clínica", "B2C", "Local", "Recorrente"],
    color: "#6ee7a8",
    icon: "shield",
    data: {
      empresa: {
        nome: "Sua Clínica",
        site: "https://suaclinica.com.br",
        instagram: "@suaclinica",
        nicho: "Clínica especializada em estética e bem-estar",
        tempo: "5 anos",
        regiao: "São Paulo / Grande SP",
        funcionarios: "14",
        estrutura: "2 médicos/especialistas, 3 recepcionistas, 2 auxiliares, 1 gestor comercial, 1 coordenador de marketing, 1 financeiro, 4 técnicos",
        vende: "Procedimentos estéticos, consultas especializadas, pacotes de tratamento e planos de manutenção mensal.",
        transformacao: "Pacientes que sofriam com insegurança ou condições estéticas/médicas recuperam confiança, autoestima e qualidade de vida com resultados visíveis e duradouros.",
        diferencial: "Atendimento humanizado, tecnologia de ponta, resultados documentados em fotos antes/depois, e plano de tratamento personalizado com acompanhamento contínuo.",
        promessa: "Resultado visível em 30 dias ou refazemos o procedimento.",
        percepcao: ["Confiável", "Premium", "Próxima", "Técnica"],
      },
      icp: {
        segmento: "Mulheres e homens entre 28 e 55 anos, classe B e A",
        setor: "B2C — atendimento direto ao consumidor",
        modelo: "B2C",
        icp_desc: "Mulher entre 30 e 50 anos, classe B/A, que investe em bem-estar, se preocupa com aparência e tem renda disponível para cuidados estéticos. Pesquisa antes de decidir, valoriza indicação e antes/depois reais. Pode ser paciente nova ou alguém retornando após experiência ruim em outro local.",
        ticket: "R$ 800 a R$ 3.500 por procedimento / R$ 350 a R$ 800 em planos mensais",
        fat_ideal: "Renda familiar acima de R$ 8.000/mês",
        estrutura_min: "Paciente com disponibilidade de horário e investimento confirmado",
        dor_principal: "Insatisfação com o próprio corpo ou rosto. Condição que afeta autoestima. Procedimento mal feito em outro lugar. Medo de resultado artificial ou efeitos colaterais.",
        perde_vendas: "Medo do procedimento. Falta de confiança no profissional. Preço percebido como alto sem entender o valor. Marido/companheiro que desencoraja.",
        urgencia: "Evento próximo (casamento, formatura, viagem), verão chegando, ou foto que gerou insatisfação.",
      },
      oferta: {
        oferta: "Consulta de avaliação gratuita + plano de tratamento personalizado + acompanhamento fotográfico dos resultados.",
        produtos: ["Toxina Botulínica", "Preenchimento Facial", "Bioestimuladores", "Laser", "Ultrassom Microfocado", "Peeling"],
        servicos: ["Consulta de Avaliação", "Plano de Tratamento Personalizado", "Plano de Manutenção Mensal", "Protocolo de Rejuvenescimento"],
        planos: "Procedimento Avulso: valor por sessão\nPlano Mensal (R$ 450/mês): 1 procedimento de manutenção/mês com desconto\nPlano Semestral (R$ 2.200): 6 sessões com 20% de desconto\nProtocolo Completo: diagnóstico + 4 sessões + manutenção",
        precos: "Parcelamento em até 12x no cartão sem juros. Pix com 5% de desconto. Planos com condições especiais na primeira consulta.",
        beneficios: ["Consulta de avaliação gratuita", "Antes/depois documentado", "Plano personalizado", "Profissional especializado", "Ambiente premium", "Retorno gratuito se necessário"],
        resultados: "Resultados visíveis a partir da primeira sessão. Melhora progressiva com protocolo completo. Satisfação documentada em fotos.",
        melhora: "Autoestima recuperada. Aparência mais jovem e natural. Confiança no próprio corpo.",
        economia: "Procedimento de qualidade evita o custo de retrabalho por resultado mal feito em clínica barata.",
        diferenciais: "1. Médico especialista executa todos os procedimentos\n2. Tecnologia importada de última geração\n3. Resultado natural — ninguém vai saber que você fez",
        porque: "Porque aqui você não é mais um número. Seu plano é criado especificamente para o seu rosto, seu objetivo e seu ritmo de vida.",
      },
      processo: {
        canais: ["Instagram", "Indicação", "Google", "Tráfego pago"],
        canal_top: "Instagram — 55% dos novos pacientes vêm das redes sociais",
        qualifica: "Interesse genuíno no procedimento. Expectativa alinhada com resultado possível. Disponibilidade de horário. Sem contraindicação médica.",
        desqualifica: "Contraindicação médica para o procedimento. Expectativa irreal (\"quero ficar como a celebridade X\"). Paciente que veio só para \"ver o preço\".",
        reuniao: "Sim",
        script: "Sim",
        apresentacao: "Não",
        fechamento: "Consulta gratuita (30 min) → apresentação do plano de tratamento → proposta financeira → agendamento do primeiro procedimento.",
        proposta: "Apresentada pessoalmente na consulta, com antes/depois de casos similares e simulação do resultado esperado.",
        negociacao: "Desconto no plano: sim. Desconto em procedimento avulso: não. Parcelamento flexível é o principal argumento de acessibilidade.",
        entregam: "Foto de antes no primeiro atendimento. Procedimento realizado pelo especialista. Orientações pós-procedimento por escrito e via WhatsApp.",
        onboarding: "Sim",
      },
      objecoes: {
        obj_comum: "\"Tenho medo de ficar com cara de plástico / artificial.\"",
        obj_lista: ["Preço alto", "Medo de dor", "Medo de resultado ruim", "Vou pensar", "Falar com marido/esposa"],
        impede: "Medo e insegurança. Falta de confiança no profissional. Experiência ruim anterior.",
        inseguranca: "\"E se não gostar?\" — retorno gratuito incluído. \"Vai doer?\" — anestesia tópica em todos os procedimentos.",
      },
      metricas: {
        conversao: "65% (consulta → agendamento)",
        ticket_med: "R$ 1.800 por visita",
        cac: "R$ 180",
        tempo_fech: "Na consulta (1 dia)",
        vol_leads: "120 consultas/mês",
        meta: "Meta: 200 atendimentos/mês. Ticket médio de R$ 2.200. 40% dos pacientes em plano de manutenção.",
        sla: "Retorno de mensagem em até 2h. Agenda disponível em até 5 dias. Retorno pós-procedimento em 30 dias.",
      },
      operacao: {
        crm: "Nuvem Fiscal + planilha customizada (em transição para CRM dedicado)",
        whats: "WhatsApp Business — recepção faz primeiro contato, gestor de relacionamento acompanha",
        ferramentas: ["WhatsApp Business", "Instagram", "Google Agenda", "Canva", "CapCut"],
        equipe: "2 especialistas, 3 recepcionistas (agendamento e recepção), 1 coordenador comercial (follow-up e planos), 1 marketing",
        funis: "Funil de Aquisição: Lead > Consulta Agendada > Consulta Realizada > Procedimento Agendado\nFunil de Retenção: Paciente Ativo > Retorno > Plano de Manutenção",
        processos: "Lead entra pelo Instagram → recepção responde em 2h → agendamento da consulta → confirmação D-1 → consulta → follow-up D+3 → retorno agendado.",
        gargalos: "Taxa de no-show acima de 20%. Follow-up de leads que não agendaram é inconsistente. Retenção de pacientes após o primeiro procedimento precisa melhorar.",
      },
      tom: {
        formal: 35,
        agressiva: 20,
        consultiva: 85,
        tecnica: 45,
        palavras_sim: ["natural", "resultado", "autoestima", "personalizado", "seguro", "especialista", "confiança"],
        palavras_nao: ["barato", "promoção relâmpago", "milagre", "antes e depois fake", "garantia total"],
        exemplo: "Oi Carla! Vi que você tem interesse em harmonização facial. Aqui trabalhamos com resultado natural — ninguém vai saber que você fez, só que você está mais bonita. Sua consulta de avaliação é gratuita e sem compromisso. Posso te mostrar alguns casos parecidos com o que você busca?",
      },
      cases: {
        cases: "Maria S. — protocolo de 3 sessões, ganhou 8 anos de juventude natural\nRoberta P. — superou insegurança pós-gravidez, autoestima completamente restaurada\nCarlos M. — harmonização masculina, resultado discreto e profissional",
        resultados: "NPS de 91. 78% dos pacientes retornam para manutenção. Média de 2,3 procedimentos por paciente/ano.",
        roi: "Plano semestral tem ROI de 3x comparado a procedimentos avulsos pela frequência e resultado acumulado",
        depoimentos: "\"Fiz 3 procedimentos em outros lugares e nunca fiquei satisfeita. Aqui foi a primeira vez que amei o resultado.\" — Juliana, 38 anos",
      },
      material: { obs_material: "Temos portfólio de antes/depois (com autorização). Fotos do espaço e dos equipamentos disponíveis." },
    },
  },

  /* ──────────────────────────────────────────────────────
   * 05. IMOBILIÁRIA / INCORPORADORA
   * ────────────────────────────────────────────────────── */
  {
    id: "imobiliaria",
    name: "Imobiliária / Incorporadora",
    description: "Vendas de imóveis, lançamentos e locações com estrutura comercial e digital bem definida.",
    tags: ["Imóveis", "B2C", "Alto Ticket", "Lançamentos"],
    color: "#ffb547",
    icon: "building",
    data: {
      empresa: {
        nome: "Sua Imobiliária",
        site: "https://suaimobiliaria.com.br",
        instagram: "@suaimobiliaria",
        nicho: "Imóveis residenciais de médio e alto padrão",
        tempo: "8 anos",
        regiao: "São Paulo — Zona Sul e Grande ABC",
        funcionarios: "22",
        estrutura: "1 diretor comercial, 8 corretores, 1 coordenador de marketing, 2 analistas digitais, 1 SDR (pré-atendimento digital), 3 administrativo, 1 jurídico, 2 gestores de locação",
        vende: "Compra, venda e locação de imóveis residenciais de médio e alto padrão. Lançamentos de incorporadoras parceiras. Assessoria completa do processo.",
        transformacao: "Compradores que tinham medo e insegurança no processo de compra do imóvel realizam o sonho com segurança, transparência e sem surpresas.",
        diferencial: "Atendimento do primeiro contato ao registro em cartório. Corretor exclusivo por cliente. Assessoria jurídica e financeira incluída.",
        promessa: "Do primeiro contato às chaves na mão — do seu lado em cada etapa.",
        percepcao: ["Confiável", "Premium", "Próxima", "Técnica"],
      },
      icp: {
        segmento: "Famílias e investidores de imóveis residenciais",
        setor: "B2C — alto ticket",
        modelo: "B2C",
        icp_desc: "Família de classe B/A buscando primeiro imóvel ou upgrade. Faixa de 30 a 50 anos. Renda familiar acima de R$ 10k/mês. Ou investidor pessoa física buscando rentabilidade em locação ou revenda. Pesquisa muito antes de decidir, precisa de confiança e acompanhamento.",
        ticket: "R$ 350.000 a R$ 1.500.000",
        fat_ideal: "Renda familiar acima de R$ 10.000/mês para compra. Patrimônio acima de R$ 500k para investidor.",
        estrutura_min: "Pré-aprovação bancária ou capital próprio disponível",
        dor_principal: "Medo de dar um passo errado em uma decisão de décadas. Processo burocrático e confuso. Não saber se o preço é justo. Medo de golpe ou problema jurídico.",
        perde_vendas: "Cliente sem pré-aprovação de crédito. Indecisão entre regiões ou tipos de imóvel. Interferência de terceiros (pais, cônjuge) sem alinhamento.",
        urgencia: "Aluguel subindo, filho nascendo, casamento próximo, oportunidade de investimento com prazo, ou lançamento com tabela de preços por tempo limitado.",
      },
      oferta: {
        oferta: "Assessoria completa na compra ou venda do imóvel: busca, visitas, negociação, financiamento, documentação e pós-venda.",
        produtos: ["Imóveis Prontos para Morar", "Lançamentos de Incorporadoras", "Imóveis para Investimento", "Imóveis de Locação"],
        servicos: ["Assessoria de Compra", "Assessoria de Venda", "Consultoria de Investimento Imobiliário", "Gestão de Locação"],
        planos: "Comprador: sem custo (comissão paga pelo vendedor)\nVendedor: 5% a 6% de comissão sobre o valor de venda\nInvestidor: consultoria personalizada com análise de rentabilidade\nLocação: taxa de administração de 8% a 10% do aluguel",
        precos: "Comissão padrão do mercado. Possibilidade de negociação para portfolio de imóveis. Sem cobrança antecipada.",
        beneficios: ["Corretor exclusivo dedicado", "Assessoria jurídica gratuita", "Simulação de financiamento inclusa", "Acompanhamento até o registro", "Portfólio de 300+ imóveis", "Pré-aprovação em 24h"],
        resultados: "Imóvel vendido em média em 45 dias. 94% dos clientes fecham dentro do orçamento planejado. 100% dos contratos revisados por advogado.",
        melhora: "Cliente compra com segurança e sem surpresas. Vendedor não precisa se preocupar com nada.",
        economia: "Negociação profissional gera desconto médio de 8% sobre o preço pedido. Documentação correta evita custos jurídicos futuros.",
        diferenciais: "1. Corretor dedicado exclusivo — não divide atenção entre 50 clientes\n2. Assessoria jurídica inclusa — sem custo extra\n3. Do primeiro contato ao cartório — acompanhamento completo",
        porque: "Porque comprar um imóvel é uma das maiores decisões da sua vida. Você merece ter alguém que conhece o mercado, cuida da burocracia e defende seus interesses do início ao fim.",
      },
      processo: {
        canais: ["Instagram", "Google", "Indicação", "Portais (Zap, Viva Real)", "Tráfego pago"],
        canal_top: "Portais imobiliários + Google — 45% dos leads qualificados",
        qualifica: "BANT: budget (pré-aprovação ou capital próprio?), authority (quem decide junto?), need (comprar, vender ou investir?), timeline (urgência real?). Mínimo: pré-aprovação de crédito ou capital próprio confirmado.",
        desqualifica: "Sem capacidade financeira comprovada. Apenas \"explorando\" sem intenção real de compra nos próximos 90 dias.",
        reuniao: "Sim",
        script: "Sim",
        apresentacao: "Não",
        fechamento: "Atendimento inicial (presencial ou vídeo) → curadoria de imóveis → visitas → proposta de compra → negociação → assinatura do contrato → documentação → chaves.",
        proposta: "Proposta de compra formal com valor, condições e prazo. Assessoria na negociação com o vendedor.",
        negociacao: "Negociamos em nome do comprador. Desconto médio conseguido: 7% a 12% sobre o preço pedido.",
        entregam: "Acompanhamento jurídico do contrato. Assistência no financiamento. Presença no cartório na assinatura. Entrega das chaves.",
        onboarding: "Sim",
      },
      objecoes: {
        obj_comum: "\"Vou esperar o mercado melhorar para comprar.\"",
        obj_lista: ["Preço alto", "Não é o momento", "Vou pensar", "Mercado incerto", "Falar com familiar"],
        impede: "Medo de tomar a decisão errada. Indecisão entre opções. Cônjuge com opinião diferente.",
        inseguranca: "\"Como sei que o preço é justo?\" — fazemos análise comparativa de mercado. \"E a documentação?\" — advogado incluso.",
      },
      metricas: {
        conversao: "12% (lead → visita) / 38% (visita → proposta) / 65% (proposta → fechamento)",
        ticket_med: "R$ 580.000",
        cac: "R$ 2.400",
        tempo_fech: "52 dias",
        vol_leads: "280/mês",
        meta: "Meta: 18 vendas/mês. VGV alvo: R$ 10M/mês. Foco em lançamentos que trazem maior rentabilidade.",
        sla: "Primeiro contato em até 30 minutos. Curadoria de imóveis em 24h. Visita agendada em até 48h.",
      },
      operacao: {
        crm: "Salesforce (customizado para imobiliário)",
        whats: "WhatsApp Business + SDR dedicado para primeiro contato em 30 min",
        ferramentas: ["Salesforce", "Zap Imóveis", "Viva Real", "OLX", "Google Ads", "Instagram Ads", "DocuSign"],
        equipe: "1 diretor comercial, 8 corretores (cada um com carteira de 20-30 clientes ativos), 1 SDR (primeiro contato leads digitais), 1 marketing, 2 analistas digitais",
        funis: "Funil Digital: Lead > Qualificação (SDR) > Atendimento (Corretor) > Visita > Proposta > Contrato\nFunil de Relacionamento: Cliente > Pós-venda > Indicação > Novo negócio",
        processos: "Lead entra → SDR contata em 30 min → qualifica e transfere para corretor → corretor agenda visita em 48h → visita → feedback 24h após → proposta → negociação.",
        gargalos: "Velocidade de atendimento ao lead digital ainda abaixo do ideal (meta: 15 min, realidade: 45 min). Reativação de leads frios inconsistente. Pós-venda pouco estruturado para gerar indicações.",
      },
      tom: {
        formal: 50,
        agressiva: 30,
        consultiva: 80,
        tecnica: 50,
        palavras_sim: ["sonho", "investimento", "segurança", "patrimônio", "localização", "qualidade de vida", "exclusivo"],
        palavras_nao: ["oportunidade imperdível", "último disponível", "preço mínimo", "urgente"],
        exemplo: "Oi Ricardo, vi que você tem interesse em imóveis no Brooklin. Temos 3 opções dentro do seu perfil com análise de rentabilidade já feita. Seria possível uma conversa rápida de 20 minutos para eu entender melhor o que você busca e te mostrar o que faz mais sentido?",
      },
      cases: {
        cases: "Família Souza — primeiro apê no Itaim Bibi, fechado em 38 dias dentro do orçamento\nInvestidor Paulo — portfólio de 3 imóveis em 18 meses, rentabilidade de 0,8% a.m.\nDr. Ana — sala comercial + apartamento no Brooklin, processo completo em 60 dias",
        resultados: "Tempo médio de venda: 45 dias. NPS: 88. 62% dos clientes indicam pelo menos 1 pessoa.",
        roi: "Imóveis vendidos com desconto médio de 8% sobre o preço pedido para o comprador",
        depoimentos: "\"Comprei meu primeiro apartamento sem estresse nenhum. Eles cuidaram de absolutamente tudo.\" — família Mendes",
      },
      material: { obs_material: "Portfólio atualizado de imóveis disponível. Material de lançamentos com tabela de preços. Modelos de contrato revisados pelo jurídico." },
    },
  },
];
